import type { SiteContent } from './types'

const en: SiteContent = {
  common: {
    home: 'Home',
    breadcrumb: 'Breadcrumb',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    learnMore: 'Learn more',
    whatsappText: "Hi Suntec, I'm interested in a solar installation.",
    whatsappLabel: 'Chat with Suntec on WhatsApp',
    logoAlt: 'Suntec Solar logo',
  },
  nav: { home: 'Home', about: 'About Us', products: 'Products', projects: 'Projects', quote: 'Get a Free Quote' },
  topbar: { tagline: 'MNRE enlisted system integrator · PM Surya Ghar registered vendor', taglineShort: 'MNRE Enlisted' },
  footer: {
    blurb: 'Suntec Renewable Systems — a Coimbatore-based MSME delivering solar PV & solar thermal EPC solutions from 1 kWp to MW scale since 2012.',
    quickLinks: 'Quick Links',
    solutions: 'Solutions',
    reachUs: 'Reach Us',
    links: { about: 'About Us', products: 'Products & Services', projects: 'Projects & Clients', contact: 'Contact / Enquiry' },
    solutionLinks: { onGrid: 'On-Grid Solar', hybrid: 'Hybrid Solar', offGrid: 'Off-Grid Solar', pumping: 'Solar Water Pumping', power: 'UPS, Batteries & Stabilizers' },
    rights: 'All rights reserved.',
    registrations: 'Laghu Udyog Bharati (MSME) Member · TEDA Empanelled',
  },

  home: {
    seo: {
      title: 'Suntec Solar | Rooftop Solar EPC Company in Coimbatore – On-Grid, Hybrid & Solar Pumps',
      description:
        'Suntec Renewable Systems, Coimbatore – MNRE enlisted solar system integrator & PM Surya Ghar vendor. On-grid, hybrid, off-grid solar and solar water pumps from 1 kWp to MW. 2.5+ MWp installed in Tamil Nadu.',
    },
    badges: ['MNRE Enlisted', 'PM Surya Ghar Vendor', 'TEDA Empanelled'],
    heroTitle: 'Solar power solutions in Coimbatore for',
    heroTitleHighlight: 'business & home',
    heroLead:
      'Suntec Renewable Systems designs, supplies and installs solar PV and solar thermal systems from 1 kWp to MW scale — for industries, commercial spaces, institutions, homes and farms across Tamil Nadu.',
    heroImageAlt: 'Large industrial rooftop solar plant installed by Suntec',
    heroCta: 'Get a Free Site Survey →',
    heroCtaSecondary: 'Explore Solutions',
    stats: [
      { label: 'Solar operations since' },
      { label: 'Installed in Tamil Nadu' },
      { value: '1 kWp – MW', label: 'Project scale' },
      { value: 'MSME', label: 'Laghu Udyog Bharati member' },
    ],
    who: {
      eyebrow: 'Who we are',
      title: 'A trusted solar EPC partner from Coimbatore',
      text: 'Suntec Renewable Systems — known as SUNTEC SOLAR — is an MSME supplier of Solar Photovoltaic (SPV) and Solar Thermal power systems. For over a decade we have earned the trust of leading industries, educational institutions and homeowners with dependable green energy solutions.',
      points: [
        'Government (MNRE) enlisted system integrator for solar PV',
        'Registered vendor under the PM Surya Ghar scheme',
        'End-to-end EPC: design, procurement, installation, commissioning & service',
        'On-grid and off-grid systems under our own SUNTEC™ brand',
      ],
      cta: 'More About Us',
      imageAlt: 'Suntec installation team on a completed rooftop solar plant',
    },
    why: {
      eyebrow: 'Why solar?',
      title: 'Five reasons to switch to solar today',
      items: [
        'Drastically reduce your electricity bills',
        'Earn a great return on your investment',
        'Protect against rising energy costs',
        'Protect the environment',
        'Stay competitive in the market',
      ],
    },
    solutions: {
      eyebrow: 'Our solutions',
      title: 'Solar systems tailored to your needs',
      text: 'Whether you want to cut grid dependence, keep the lights on during power cuts, or run farm pumps on sunlight — we design the right system for your site.',
      cards: [
        { title: 'On-Grid Solar System', text: 'Connected to the utility grid with net metering — export surplus power and earn credits on your EB bill.', link: 'Learn more about on-grid →', imageAlt: 'On-grid rooftop solar on GI sheet roof' },
        { title: 'Hybrid Solar System', text: 'Solar panels, a hybrid inverter and battery storage for uninterrupted power — even during outages.', link: 'Learn more about hybrid →', imageAlt: 'Hybrid rooftop solar on an RCC building' },
        { title: 'Solar Water Pumping', text: 'Reliable, diesel-free irrigation and water supply powered by the sun for agriculture and estates.', link: 'Learn more about solar pumps →', imageAlt: 'Ground-mounted solar array for water pumping' },
      ],
    },
    triangle: {
      eyebrow: 'How we size your plant',
      title: 'The Suntec Triangular Approach',
      text: 'We use three parameters together to decide the right solar capacity for every customer — so you never over-pay or under-build.',
      params: ['Average EB consumption', 'Investment capacity', 'Shadow-free space available'],
      note: "Share your EB tariff type, consumer number and roof type — we'll do a site survey and energy audit (if required), finalise the capacity and send you a quote.",
      cta: 'Book a Site Visit',
      imageAlt: 'SolarEdge 100 kW inverter installation with accessories',
    },
    clients: { eyebrow: 'Trusted by', title: 'Industries & institutions that rely on us', all: 'See all clients & projects →' },
    faq: {
      eyebrow: 'FAQ',
      title: 'Frequently asked questions',
      items: [
        { q: 'How does Suntec decide the right solar capacity for my site?', a: 'We use our Triangular Approach, which balances three parameters: your average EB consumption, your investment capacity and the shadow-free space available on your roof or ground.' },
        { q: 'What details do you need before a site visit?', a: 'Your type of customer based on EB tariff, your EB consumer number (SC No.) with the registered phone number, and the type of roof available — flat RCC, galvanized (GI) taper sheet or ground.' },
        { q: 'What is the difference between an on-grid and a hybrid solar system?', a: 'An on-grid system is connected to the utility grid and exports surplus power through net metering, but does not provide backup during outages. A hybrid system adds a hybrid inverter and batteries so your essential loads keep running during power cuts.' },
        { q: 'Is Suntec a registered vendor for the PM Surya Ghar scheme?', a: 'Yes. Suntec is a government (MNRE) enlisted system integrator for solar PV systems registered under the PM Surya Ghar scheme, and an empanelled vendor with TEDA.' },
        { q: 'Which areas and project sizes do you handle?', a: 'We serve customers across Tamil Nadu from our Coimbatore office, with systems from 1 kWp for homes up to MW-scale plants for industries, institutions and agriculture.' },
      ],
    },
    cta: { title: 'Ready to cut your electricity bill?', text: 'Talk to our solar experts for a free consultation and site survey.', label: 'Send an Enquiry' },
  },

  about: {
    seo: {
      title: 'About Suntec Renewable Systems | Solar EPC Company in Coimbatore since 2012',
      description: 'Suntec Renewable Systems is a Coimbatore MSME solar EPC company operating since 2012 — MNRE enlisted, PM Surya Ghar registered and TEDA empanelled, with 2.5+ MWp installed.',
    },
    hero: { title: 'About Suntec Renewable Systems', subtitle: "Over a decade of engineering clean, reliable solar power for Tamil Nadu's industries, institutions and homes.", crumb: 'About Us' },
    overview: {
      eyebrow: 'Company overview',
      title: 'Green energy solutions from 1 kWp to MW scale',
      paragraphs: [
        'We, Suntec Renewable Systems — known as SUNTEC SOLAR — are an MSME company and a supplier of Solar Photovoltaic (SPV) & Solar Thermal power systems based in Coimbatore. We provide green energy solutions for industrial, commercial, educational institutions, home and agricultural applications.',
        'We commenced our solar division operations in 2012, and over a decade we have won the trust of our prestigious customers. We are a government (MNRE) enlisted system integrator for solar PV systems registered under the PM Surya Ghar scheme.',
        'As an EPC company, we design and tailor both on-grid and off-grid solar applications and offer standard PV solutions under the brand name SUNTEC™. So far we have executed and installed solar power plants of over 2.5 MWp in Tamil Nadu.',
      ],
      imageAlt: 'Large rooftop solar plant installed by Suntec',
    },
    vision: {
      title: 'Our Vision',
      text: 'To be the most trusted provider of integrated solar EPC solutions for industrial, commercial, and residential sectors — driving a cleaner, more energy-efficient world through smart, scalable, and sustainable solar technologies.',
    },
    mission: {
      title: 'Our Mission',
      text: 'To empower industries, businesses, and homeowners with reliable, cost-effective solar energy systems by delivering end-to-end EPC services — from expert design and procurement to seamless installation and ongoing support. We are committed to engineering excellence, customer-centric service, and creating long-term environmental and economic value for every client we serve.',
    },
    values: {
      eyebrow: 'Core values',
      title: 'What we stand for',
      items: [
        { icon: '🌱', title: 'Sustainability', text: 'Building a greener future with clean, renewable energy that reduces environmental impact and carbon emissions.' },
        { icon: '🤝', title: 'Integrity', text: 'Transparency, honesty and accountability with clients, partners, employees and communities.' },
        { icon: '⚙️', title: 'Excellence in Engineering', text: 'High-performance systems through precision engineering, quality materials and industry best practices.' },
        { icon: '🎯', title: 'Customer-Centric', text: 'Tailored, value-driven energy solutions for every residential, commercial or industrial need.' },
        { icon: '🚀', title: 'Innovation', text: 'Embracing new technologies and smart design to offer cutting-edge solar solutions.' },
        { icon: '🦺', title: 'Safety First', text: 'The highest health and safety standards for our teams and stakeholders on every site.' },
        { icon: '🔋', title: 'Reliability & Long-Term Value', text: 'We stand by our systems for long-term performance, durability and ROI.' },
        { icon: '🧩', title: 'Collaboration', text: 'Strong partnerships with clients, suppliers and communities for shared success.' },
      ],
    },
    certs: {
      eyebrow: 'Certifications & registrations',
      title: 'Recognised and empanelled',
      items: [
        { icon: '🏅', title: 'Laghu Udyog Bharati Member', text: 'Registered MSME enterprise.' },
        { icon: '⚡', title: 'TEDA Empanelled Vendor', text: 'Tamil Nadu Energy Development Agency.' },
        { icon: '🏠', title: 'PM Surya Ghar Registered', text: 'MNRE enlisted vendor for the residential rooftop solar scheme.' },
      ],
    },
    establishments: {
      eyebrow: 'Our establishments',
      title: 'Two companies, one commitment to quality',
      labels: { partners: 'Partners', proprietor: 'Proprietor', gst: 'GST No.', address: 'Address', email: 'Email', enquiry: 'Enquiry', service: 'Service', activity: 'Activity', teams: 'Teams' },
      renewable: {
        meta: 'Est. 2019 · Partnership',
        activity: 'Product design, procurement, installation, commissioning & service',
        teams: 'Marketing · Design · Procurement · Implementation & Service',
        products: ['Solar on-grid system', 'Solar off-grid system', 'Solar hybrid system', 'Solar pumping'],
      },
      power: {
        meta: 'Est. 2016 · Proprietorship',
        activity: 'Sales & service',
        teams: 'Procurement · Sales & Service',
        products: ['Solar water heater', 'Servo voltage stabilizer', 'Online UPS', 'Domestic UPS & tubular batteries', 'Lithium, automotive & industrial batteries'],
      },
    },
    cta: { title: "Let's plan your solar project", text: 'Free consultation, site survey and transparent quotation.', label: 'Contact Us' },
  },

  products: {
    seo: {
      title: 'Solar Products & Services | On-Grid, Hybrid, Off-Grid Solar & Solar Pumps – Suntec Coimbatore',
      description: 'On-grid, hybrid and off-grid rooftop solar systems, solar water pumping, mounting structures, solar water heaters, UPS, batteries and servo stabilizers from Suntec, Coimbatore.',
    },
    hero: { title: 'Solar Products & Services', subtitle: 'Complete solar EPC solutions — designed, supplied, installed, commissioned and serviced by Suntec.', crumb: 'Products & Services' },
    componentsTitle: 'Key components',
    systems: {
      onGrid: {
        tag: 'SOLAR PV · GRID-TIED',
        title: 'On-Grid Solar System',
        intro: 'An on-grid solar system is connected to your local electricity grid. It lets you use solar energy during the day and switch to grid power at night or when solar production is low.',
        points: ['Excess electricity is sent back to the grid, earning you credits or payments via net metering.', 'Lowest cost per kW — the fastest payback for homes, industries and institutions.', 'No power backup during outages unless combined with batteries.'],
        components: ['Solar panel', 'DCDB', 'Inverter – grid tie', 'ACDB', 'MMS (mounting)', 'DC cables', 'AC cables', 'Lightning arrester', 'Earthing accessories'],
        imageAlt: 'On-grid solar system diagram: solar panels, DCDB, grid-tie inverter, ACDB, net meter and utility grid',
        enquireLabel: 'Enquire about On-Grid',
      },
      hybrid: {
        tag: 'SOLAR PV · BATTERY BACKUP',
        title: 'Hybrid Solar System',
        intro: 'A hybrid solar system combines solar panels, a hybrid inverter and battery storage to ensure uninterrupted power — even during outages. Critical loads stay on while surplus energy can still be exported to the grid.',
        points: ['Backup for essential loads during power cuts', 'Net-metering benefits like an on-grid system', 'Ideal for hospitals, schools, offices and homes'],
        components: ['Solar panel', 'DCDB', 'Hybrid inverter', 'ACDB', 'MMS (mounting)', 'DC cables', 'AC cables', 'Lightning arrester', 'Earthing accessories', 'Battery box', 'Battery'],
        imageAlt: 'Hybrid solar system diagram with battery, backup load, net meter and utility grid',
        enquireLabel: 'Enquire about Hybrid',
      },
      offGrid: {
        tag: 'SOLAR PV · STANDALONE',
        title: 'Off-Grid Solar System',
        intro: 'A standalone system with battery storage for locations where grid power is unavailable or unreliable — farmhouses, remote sites and estates. Generate, store and use your own power with complete independence from the grid.',
        points: ['Full energy independence', 'Sized to your daily load and backup hours', 'Available as standard SUNTEC™ packaged solutions'],
        imageAlt: 'Rooftop solar panels on an RCC building',
        enquireLabel: 'Enquire about Off-Grid',
      },
      pumping: {
        tag: 'AGRICULTURE',
        title: 'Solar-Driven Water Pumping',
        intro: 'Run borewell and surface pumps directly on solar energy — no diesel, no grid dependency, and near-zero running cost. Perfect for agriculture, estates, tea gardens and water supply schemes.',
        points: ['Eliminates diesel and electricity costs for irrigation', 'Ground-mounted arrays engineered for open fields', 'Low maintenance, long service life'],
        imageAlt: 'Ground-mounted solar array in an open field',
        enquireLabel: 'Enquire about Solar Pumps',
      },
    },
    mounting: {
      eyebrow: 'Mounting structures',
      title: 'Engineered for every roof and site',
      text: 'We design module mounting structures (MMS) to suit your building and site conditions.',
      items: [
        { title: 'GI Sheet / Tapered Roof', text: 'Panel mounting on GI roofs with walkways and safety railings for industrial sheds.' },
        { title: 'Flat RCC Roof', text: 'Flat roof structures on RCC buildings with movable weights — no drilling into your roof.' },
        { title: 'Ground Mounted', text: 'Robust ground-mounted structures for open land, farms and MW-scale plants.' },
      ],
    },
    power: {
      eyebrow: 'Suntec Power Systems',
      title: 'Power backup & solar thermal products',
      text: 'Sales and service through our sister concern, Suntec Power Systems (since 2016).',
      items: [
        { icon: '🚿', title: 'Solar Water Heater', text: 'Hot water from sunlight for homes, hostels, hospitals and hotels.' },
        { icon: '📈', title: 'Servo Voltage Stabilizer', text: 'Protects machinery and equipment from voltage fluctuations.' },
        { icon: '🖥️', title: 'Online UPS', text: 'Zero-changeover backup for servers, labs and critical equipment.' },
        { icon: '🏠', title: 'Domestic UPS & Tubular Batteries', text: 'Reliable home inverters with long-life tubular batteries.' },
        { icon: '🔋', title: 'Lithium Batteries', text: 'Compact, long-cycle storage for solar and backup applications.' },
        { icon: '🚗', title: 'Automotive & Industrial Batteries', text: 'Batteries for vehicles, gensets and industrial applications.' },
      ],
      cta: 'Enquire about Power Products',
    },
    process: {
      eyebrow: 'Our process',
      title: 'From enquiry to power generation',
      steps: [
        { strong: 'Share basic details', text: ' — EB tariff type, consumer (SC) number & registered phone, and roof type (Flat RCC, GI taper or ground).' },
        { strong: 'Site survey & energy audit', text: ' (if required) by our engineers.' },
        { strong: 'Capacity design', text: ' using our Triangular Approach — consumption, investment and shadow-free space.' },
        { strong: 'Quotation, procurement & installation', text: ' with quality partner brands.' },
        { strong: 'Commissioning, net-meter liaison & after-sales service.', text: '' },
      ],
      cta: 'Start Your Enquiry',
      imageAlt: 'Suntec triangular approach: average EB consumption, investment capacity and shadow-free space decide solar capacity',
    },
  },

  projects: {
    seo: {
      title: 'Solar Projects & Clients | 2.5+ MWp Installed in Tamil Nadu – Suntec Solar',
      description: 'Rooftop and ground-mounted solar plants by Suntec for PSG Institutions, Avinashilingam University, textile mills, CNC manufacturers, hospitals and schools across Tamil Nadu.',
    },
    hero: { title: 'Solar Projects & Clients', subtitle: 'Over 2.5 MWp of solar power plants executed across Tamil Nadu.', crumb: 'Projects' },
    featured: { eyebrow: 'Case studies', title: 'Featured installations', view: 'View project →' },
    gallery: {
      eyebrow: 'Gallery',
      title: 'Our work on the ground',
      captions: ['Panel mounting on GI roof', 'SolarEdge 100 kW inverter with accessories', 'Flat roof structure on RCC with movable weights', 'Ground-mounted structure', 'Our installation team'],
    },
    clients: { eyebrow: 'Our major clients', title: 'Trusted by leading organisations' },
    partners: { eyebrow: 'Technology partners', title: 'We work with top solar brands' },
    industries: {
      eyebrow: 'Industries we serve',
      title: 'Solar expertise for energy-intensive sectors',
      items: [
        { icon: '🧵', name: 'Textile Spinning Mills' },
        { icon: '🧶', name: 'Knitting Units' },
        { icon: '🏢', name: 'Commercial Establishments' },
        { icon: '🛠️', name: 'CNC Component Manufacturing' },
        { icon: '🍃', name: 'Tea Industry' },
      ],
    },
    cta: { title: 'Want results like these?', text: "Tell us about your site and we'll design the right system.", label: 'Get a Quote' },
  },

  caseStudy: {
    seoTitle: '{client} Solar Plant, {location} | Suntec Solar Project',
    seoDescription: 'Case study: {capacity} solar power plant installed by Suntec Renewable Systems for {client}, {location}.',
    crumb: 'Projects',
    facts: { capacity: 'Capacity', system: 'System type', mounting: 'Mounting', location: 'Location', year: 'Commissioned', sector: 'Sector' },
    overview: 'Project overview',
    highlights: 'Highlights',
    gallery: 'Project photos',
    draft: 'DRAFT — not published. Fill in the project details in app/data/projects.ts and set published: true.',
    back: '← All projects',
    cta: { title: 'Planning a similar project?', text: 'Get a free site survey and capacity recommendation.', label: 'Get a Quote' },
  },

  contact: {
    seo: {
      title: 'Contact Suntec Solar | Free Solar Site Survey & Quote in Coimbatore',
      description: 'Request a free solar site survey and quote from Suntec Renewable Systems, Kovilpalayam, Coimbatore. Call 98435 02872 / 82480 33140 or send an enquiry online.',
    },
    hero: { title: 'Get a Free Solar Quote', subtitle: 'Tell us about your requirement — our team will get back to you within one working day.', crumb: 'Contact' },
    checklist: {
      title: 'Helpful to have ready before our site visit',
      items: ['Type of customer — based on EB tariff', 'EB consumer number (SC No.) and registered phone number', 'Type of roof — Flat RCC, Galvanized (GI) taper, or Ground'],
    },
    info: { title: 'Contact information', office: 'Head office', sales: 'Sales enquiry', service: 'Service', email: 'Email' },
    mapTitle: 'Suntec office location on Google Maps',
  },

  form: {
    name: 'Full name',
    phone: 'Mobile number',
    phonePlaceholder: '10-digit mobile',
    email: 'Email',
    city: 'City / Location',
    customerType: 'Customer type (EB tariff)',
    product: 'Interested in',
    roofType: 'Roof / site type',
    monthlyBill: 'Average monthly EB bill (₹)',
    monthlyBillPlaceholder: 'e.g. 8000',
    ebNumber: 'EB consumer number (SC No.)',
    ebHint: 'Optional — helps us check your sanctioned load and tariff.',
    message: 'Your requirement',
    messagePlaceholder: 'Tell us about your site, load or any questions',
    select: 'Select…',
    submit: 'Submit Enquiry',
    sending: 'Sending…',
    success: 'Thank you! Your enquiry has been received. Our team will contact you within one working day.',
    notConfigured: 'Online enquiries are not configured yet.',
    failed: "Sorry, we couldn't send your enquiry.",
    fallback: 'Please call us on {phone} or email {email}.',
    errors: { name: 'Please enter your name.', phone: 'Please enter a valid 10-digit mobile number.', email: 'Please enter a valid email address.' },
    options: {
      customerTypes: {
        'Domestic / Residential': 'Domestic / Residential',
        Commercial: 'Commercial',
        'Industrial (LT)': 'Industrial (LT)',
        'Industrial (HT)': 'Industrial (HT)',
        'Educational Institution': 'Educational Institution',
        Agricultural: 'Agricultural',
        Other: 'Other',
      },
      products: {
        'On-Grid Solar': 'On-Grid Solar',
        'Hybrid Solar': 'Hybrid Solar',
        'Off-Grid Solar': 'Off-Grid Solar',
        'Solar Water Pumping': 'Solar Water Pumping',
        'Solar Water Heater': 'Solar Water Heater',
        'UPS / Batteries / Stabilizer': 'UPS / Batteries / Stabilizer',
        'PM Surya Ghar (Residential Subsidy)': 'PM Surya Ghar (Residential Subsidy)',
        'Not sure – need advice': 'Not sure – need advice',
      },
      roofTypes: { 'Flat RCC': 'Flat RCC', 'Galvanized (GI) taper sheet': 'Galvanized (GI) taper sheet', Ground: 'Ground', Other: 'Other' },
    },
  },

  error: {
    notFound: 'Page not found',
    notFoundText: "The page you're looking for doesn't exist or has moved.",
    generic: 'Something went wrong',
    genericText: 'Please try again, or contact us directly.',
    back: 'Back to Home',
  },
}

export default en
